<?php

return [
    'title' => 'nifayatech',
    'modules' => [
        'roles' => [
            'label' => 'Roles',
            'group' => 'Access Control',
            'table' => 'roles',
            'primary' => 'role_id',
            'searchable' => ['role_name', 'description'],
            'list' => ['role_id', 'role_name', 'description', 'created_at'],
            'form' => ['role_name', 'description'],
            'fields' => [
                'role_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'role_name' => ['label' => 'Role Name', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'permissions' => [
            'label' => 'Permissions',
            'group' => 'Access Control',
            'table' => 'permissions',
            'primary' => 'permission_id',
            'searchable' => ['permission_name', 'description', 'module'],
            'list' => ['permission_id', 'permission_name', 'module', 'description'],
            'form' => ['permission_name', 'module', 'description'],
            'fields' => [
                'permission_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'permission_name' => ['label' => 'Permission Name', 'type' => 'text', 'required' => true],
                'module' => ['label' => 'Module', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
            ],
        ],
        'role_permissions' => [
            'label' => 'Role Permissions',
            'group' => 'Access Control',
            'table' => 'role_permissions',
            'composite' => ['role_id', 'permission_id'],
            'allow_edit' => false,
            'searchable' => [],
            'list' => ['role_id', 'permission_id'],
            'form' => ['role_id', 'permission_id'],
            'fields' => [
                'role_id' => [
                    'label' => 'Role',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'roles', 'key' => 'role_id', 'label' => 'role_name'],
                ],
                'permission_id' => [
                    'label' => 'Permission',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'permissions', 'key' => 'permission_id', 'label' => 'permission_name'],
                ],
            ],
        ],
        'users' => [
            'label' => 'Users',
            'group' => 'Access Control',
            'table' => 'users',
            'primary' => 'user_id',
            'searchable' => ['username', 'email', 'full_name'],
            'list' => ['user_id', 'username', 'email', 'full_name', 'role_id', 'status', 'last_login'],
            'form' => ['username', 'email', 'password_hash', 'full_name', 'phone', 'role_id', 'status'],
            'fields' => [
                'user_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'username' => ['label' => 'Username', 'type' => 'text', 'required' => true],
                'email' => ['label' => 'Email', 'type' => 'email', 'required' => true],
                'password_hash' => ['label' => 'Password', 'type' => 'password', 'required' => true],
                'full_name' => ['label' => 'Full Name', 'type' => 'text', 'required' => true],
                'phone' => ['label' => 'Phone', 'type' => 'text'],
                'role_id' => [
                    'label' => 'Role',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'roles', 'key' => 'role_id', 'label' => 'role_name'],
                ],
                'status' => [
                    'label' => 'Status',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'active' => 'Active',
                        'inactive' => 'Inactive',
                        'suspended' => 'Suspended',
                    ],
                    'default' => 'active',
                ],
                'last_login' => ['label' => 'Last Login', 'type' => 'datetime', 'readonly' => true],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
                'updated_at' => ['label' => 'Updated', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'zones' => [
            'label' => 'Zones',
            'group' => 'Geography',
            'table' => 'zones',
            'primary' => 'zone_id',
            'searchable' => ['zone_name', 'zone_code', 'city', 'district'],
            'list' => ['zone_id', 'zone_name', 'zone_code', 'city', 'district', 'population'],
            'form' => ['zone_name', 'zone_code', 'city', 'district', 'population', 'area_km2', 'description'],
            'fields' => [
                'zone_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'zone_name' => ['label' => 'Zone Name', 'type' => 'text', 'required' => true],
                'zone_code' => ['label' => 'Zone Code', 'type' => 'text'],
                'city' => ['label' => 'City', 'type' => 'text'],
                'district' => ['label' => 'District', 'type' => 'text'],
                'population' => ['label' => 'Population', 'type' => 'number'],
                'area_km2' => ['label' => 'Area (km2)', 'type' => 'decimal'],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'container_types' => [
            'label' => 'Container Types',
            'group' => 'Containers',
            'table' => 'container_types',
            'primary' => 'type_id',
            'searchable' => ['type_name', 'description'],
            'list' => ['type_id', 'type_name', 'color_code', 'description'],
            'form' => ['type_name', 'color_code', 'description'],
            'fields' => [
                'type_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'type_name' => ['label' => 'Type Name', 'type' => 'text', 'required' => true],
                'color_code' => ['label' => 'Color Code', 'type' => 'text'],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
            ],
        ],
        'containers' => [
            'label' => 'Containers',
            'group' => 'Containers',
            'table' => 'containers',
            'primary' => 'container_id',
            'searchable' => ['container_code', 'address', 'neighborhood'],
            'list' => ['container_id', 'container_code', 'type_id', 'zone_id', 'current_fill_percentage', 'status', 'last_sensor_update'],
            'form' => [
                'container_code',
                'type_id',
                'capacity_liters',
                'current_fill_percentage',
                'latitude',
                'longitude',
                'address',
                'zone_id',
                'neighborhood',
                'accessibility_notes',
                'status',
                'alert_threshold',
                'installation_date',
                'last_emptied_at',
                'last_maintenance_date',
                'next_scheduled_collection',
                'sensor_id',
            ],
            'computed' => [
                'location' => ['type' => 'point', 'lat' => 'latitude', 'lng' => 'longitude'],
            ],
            'fields' => [
                'container_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'container_code' => ['label' => 'Container Code', 'type' => 'text', 'required' => true],
                'type_id' => [
                    'label' => 'Container Type',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'container_types', 'key' => 'type_id', 'label' => 'type_name'],
                ],
                'capacity_liters' => ['label' => 'Capacity (L)', 'type' => 'number', 'required' => true],
                'current_fill_percentage' => ['label' => 'Fill Percentage', 'type' => 'decimal', 'default' => 0],
                'current_fill_liters' => ['label' => 'Fill Liters', 'type' => 'decimal', 'readonly' => true],
                'latitude' => ['label' => 'Latitude', 'type' => 'decimal', 'required' => true],
                'longitude' => ['label' => 'Longitude', 'type' => 'decimal', 'required' => true],
                'location' => ['label' => 'Location', 'type' => 'text', 'readonly' => true],
                'address' => ['label' => 'Address', 'type' => 'text'],
                'zone_id' => [
                    'label' => 'Zone',
                    'type' => 'select',
                    'relation' => ['table' => 'zones', 'key' => 'zone_id', 'label' => 'zone_name'],
                ],
                'neighborhood' => ['label' => 'Neighborhood', 'type' => 'text'],
                'accessibility_notes' => ['label' => 'Accessibility Notes', 'type' => 'textarea'],
                'status' => [
                    'label' => 'Status',
                    'type' => 'select',
                    'options' => [
                        'active' => 'Active',
                        'maintenance' => 'Maintenance',
                        'damaged' => 'Damaged',
                        'decommissioned' => 'Decommissioned',
                    ],
                    'default' => 'active',
                ],
                'alert_threshold' => ['label' => 'Alert Threshold', 'type' => 'decimal', 'default' => 80],
                'installation_date' => ['label' => 'Installation Date', 'type' => 'date'],
                'last_emptied_at' => ['label' => 'Last Emptied', 'type' => 'datetime'],
                'last_maintenance_date' => ['label' => 'Last Maintenance Date', 'type' => 'date'],
                'next_scheduled_collection' => ['label' => 'Next Scheduled Collection', 'type' => 'datetime'],
                'sensor_id' => ['label' => 'Sensor ID', 'type' => 'text'],
                'last_sensor_update' => ['label' => 'Last Sensor Update', 'type' => 'datetime', 'readonly' => true],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
                'updated_at' => ['label' => 'Updated', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'sensor_readings' => [
            'label' => 'Sensor Readings',
            'group' => 'Containers',
            'table' => 'sensor_readings',
            'primary' => 'reading_id',
            'searchable' => [],
            'list' => ['reading_id', 'container_id', 'fill_percentage', 'temperature', 'humidity', 'battery_level', 'reading_timestamp'],
            'form' => ['container_id', 'fill_percentage', 'temperature', 'humidity', 'battery_level', 'signal_strength', 'reading_timestamp'],
            'fields' => [
                'reading_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'container_id' => [
                    'label' => 'Container',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'containers', 'key' => 'container_id', 'label' => 'container_code'],
                ],
                'fill_percentage' => ['label' => 'Fill Percentage', 'type' => 'decimal', 'required' => true],
                'temperature' => ['label' => 'Temperature (C)', 'type' => 'decimal'],
                'humidity' => ['label' => 'Humidity (%)', 'type' => 'decimal'],
                'battery_level' => ['label' => 'Battery Level (%)', 'type' => 'decimal'],
                'signal_strength' => ['label' => 'Signal Strength', 'type' => 'number'],
                'reading_timestamp' => ['label' => 'Reading Time', 'type' => 'datetime'],
            ],
        ],
        'employee_types' => [
            'label' => 'Employee Types',
            'group' => 'Workforce',
            'table' => 'employee_types',
            'primary' => 'type_id',
            'searchable' => ['type_name'],
            'list' => ['type_id', 'type_name'],
            'form' => ['type_name'],
            'fields' => [
                'type_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'type_name' => ['label' => 'Type Name', 'type' => 'text', 'required' => true],
            ],
        ],
        'employees' => [
            'label' => 'Employees',
            'group' => 'Workforce',
            'table' => 'employees',
            'primary' => 'employee_id',
            'searchable' => ['employee_code'],
            'list' => ['employee_id', 'employee_code', 'user_id', 'employee_type_id', 'hire_date', 'status'],
            'form' => [
                'user_id',
                'employee_code',
                'employee_type_id',
                'hire_date',
                'salary',
                'license_number',
                'license_expiry',
                'emergency_contact_name',
                'emergency_contact_phone',
                'status',
            ],
            'fields' => [
                'employee_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'user_id' => [
                    'label' => 'User',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'users', 'key' => 'user_id', 'label' => 'full_name'],
                ],
                'employee_code' => ['label' => 'Employee Code', 'type' => 'text', 'required' => true],
                'employee_type_id' => [
                    'label' => 'Employee Type',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'employee_types', 'key' => 'type_id', 'label' => 'type_name'],
                ],
                'hire_date' => ['label' => 'Hire Date', 'type' => 'date', 'required' => true],
                'salary' => ['label' => 'Salary', 'type' => 'decimal'],
                'license_number' => ['label' => 'License Number', 'type' => 'text'],
                'license_expiry' => ['label' => 'License Expiry', 'type' => 'date'],
                'emergency_contact_name' => ['label' => 'Emergency Contact Name', 'type' => 'text'],
                'emergency_contact_phone' => ['label' => 'Emergency Contact Phone', 'type' => 'text'],
                'status' => [
                    'label' => 'Status',
                    'type' => 'select',
                    'options' => [
                        'active' => 'Active',
                        'on_leave' => 'On Leave',
                        'terminated' => 'Terminated',
                    ],
                    'default' => 'active',
                ],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'work_shifts' => [
            'label' => 'Work Shifts',
            'group' => 'Workforce',
            'table' => 'work_shifts',
            'primary' => 'shift_id',
            'searchable' => ['shift_name'],
            'list' => ['shift_id', 'shift_name', 'start_time', 'end_time'],
            'form' => ['shift_name', 'start_time', 'end_time', 'description'],
            'fields' => [
                'shift_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'shift_name' => ['label' => 'Shift Name', 'type' => 'text', 'required' => true],
                'start_time' => ['label' => 'Start Time', 'type' => 'time', 'required' => true],
                'end_time' => ['label' => 'End Time', 'type' => 'time', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
            ],
        ],
        'work_timeline' => [
            'label' => 'Work Timeline',
            'group' => 'Workforce',
            'table' => 'work_timeline',
            'primary' => 'timeline_id',
            'searchable' => [],
            'list' => ['timeline_id', 'employee_id', 'shift_id', 'work_date', 'status', 'total_hours'],
            'form' => [
                'employee_id',
                'shift_id',
                'work_date',
                'clock_in',
                'clock_out',
                'break_duration_minutes',
                'status',
                'notes',
            ],
            'fields' => [
                'timeline_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'employee_id' => [
                    'label' => 'Employee',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'employees', 'key' => 'employee_id', 'label' => 'employee_code'],
                ],
                'shift_id' => [
                    'label' => 'Shift',
                    'type' => 'select',
                    'relation' => ['table' => 'work_shifts', 'key' => 'shift_id', 'label' => 'shift_name'],
                ],
                'work_date' => ['label' => 'Work Date', 'type' => 'date', 'required' => true],
                'clock_in' => ['label' => 'Clock In', 'type' => 'datetime'],
                'clock_out' => ['label' => 'Clock Out', 'type' => 'datetime'],
                'break_duration_minutes' => ['label' => 'Break Minutes', 'type' => 'number', 'default' => 0],
                'status' => [
                    'label' => 'Status',
                    'type' => 'select',
                    'options' => [
                        'scheduled' => 'Scheduled',
                        'in_progress' => 'In Progress',
                        'completed' => 'Completed',
                        'absent' => 'Absent',
                        'late' => 'Late',
                    ],
                    'default' => 'scheduled',
                ],
                'notes' => ['label' => 'Notes', 'type' => 'textarea'],
                'total_hours' => ['label' => 'Total Hours', 'type' => 'decimal', 'readonly' => true],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'vehicles' => [
            'label' => 'Vehicles',
            'group' => 'Fleet',
            'table' => 'vehicles',
            'primary' => 'vehicle_id',
            'searchable' => ['vehicle_code', 'license_plate', 'brand', 'model'],
            'list' => ['vehicle_id', 'vehicle_code', 'license_plate', 'vehicle_type', 'capacity_kg', 'operational_status'],
            'form' => [
                'vehicle_code',
                'license_plate',
                'vehicle_type',
                'brand',
                'model',
                'year',
                'capacity_kg',
                'fuel_type',
                'current_latitude',
                'current_longitude',
                'operational_status',
                'last_maintenance_date',
                'next_maintenance_date',
                'odometer_km',
                'purchase_date',
                'insurance_expiry',
            ],
            'fields' => [
                'vehicle_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'vehicle_code' => ['label' => 'Vehicle Code', 'type' => 'text', 'required' => true],
                'license_plate' => ['label' => 'License Plate', 'type' => 'text', 'required' => true],
                'vehicle_type' => [
                    'label' => 'Vehicle Type',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'truck' => 'Truck',
                        'compactor' => 'Compactor',
                        'van' => 'Van',
                        'pickup' => 'Pickup',
                    ],
                ],
                'brand' => ['label' => 'Brand', 'type' => 'text'],
                'model' => ['label' => 'Model', 'type' => 'text'],
                'year' => ['label' => 'Year', 'type' => 'number'],
                'capacity_kg' => ['label' => 'Capacity (kg)', 'type' => 'number', 'required' => true],
                'fuel_type' => [
                    'label' => 'Fuel Type',
                    'type' => 'select',
                    'options' => [
                        'diesel' => 'Diesel',
                        'petrol' => 'Petrol',
                        'electric' => 'Electric',
                        'hybrid' => 'Hybrid',
                    ],
                ],
                'current_latitude' => ['label' => 'Current Latitude', 'type' => 'decimal'],
                'current_longitude' => ['label' => 'Current Longitude', 'type' => 'decimal'],
                'operational_status' => [
                    'label' => 'Operational Status',
                    'type' => 'select',
                    'options' => [
                        'available' => 'Available',
                        'in_use' => 'In Use',
                        'maintenance' => 'Maintenance',
                        'out_of_service' => 'Out of Service',
                    ],
                    'default' => 'available',
                ],
                'last_maintenance_date' => ['label' => 'Last Maintenance Date', 'type' => 'date'],
                'next_maintenance_date' => ['label' => 'Next Maintenance Date', 'type' => 'date'],
                'odometer_km' => ['label' => 'Odometer (km)', 'type' => 'number', 'default' => 0],
                'purchase_date' => ['label' => 'Purchase Date', 'type' => 'date'],
                'insurance_expiry' => ['label' => 'Insurance Expiry', 'type' => 'date'],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
                'updated_at' => ['label' => 'Updated', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'vehicle_maintenance' => [
            'label' => 'Vehicle Maintenance',
            'group' => 'Fleet',
            'table' => 'vehicle_maintenance',
            'primary' => 'maintenance_id',
            'searchable' => ['description', 'technician_name'],
            'list' => ['maintenance_id', 'vehicle_id', 'maintenance_date', 'maintenance_type', 'cost'],
            'form' => ['vehicle_id', 'maintenance_date', 'maintenance_type', 'description', 'cost', 'technician_name', 'next_service_date', 'notes'],
            'fields' => [
                'maintenance_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'vehicle_id' => [
                    'label' => 'Vehicle',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'vehicles', 'key' => 'vehicle_id', 'label' => 'vehicle_code'],
                ],
                'maintenance_date' => ['label' => 'Maintenance Date', 'type' => 'date', 'required' => true],
                'maintenance_type' => [
                    'label' => 'Maintenance Type',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'routine' => 'Routine',
                        'repair' => 'Repair',
                        'inspection' => 'Inspection',
                        'emergency' => 'Emergency',
                    ],
                ],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'cost' => ['label' => 'Cost', 'type' => 'decimal'],
                'technician_name' => ['label' => 'Technician Name', 'type' => 'text'],
                'next_service_date' => ['label' => 'Next Service Date', 'type' => 'date'],
                'notes' => ['label' => 'Notes', 'type' => 'textarea'],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'vehicle_assignments' => [
            'label' => 'Vehicle Assignments',
            'group' => 'Fleet',
            'table' => 'vehicle_assignments',
            'primary' => 'assignment_id',
            'searchable' => ['notes'],
            'list' => ['assignment_id', 'vehicle_id', 'employee_id', 'assignment_date', 'status', 'start_time', 'end_time'],
            'form' => [
                'vehicle_id',
                'employee_id',
                'assignment_date',
                'start_time',
                'end_time',
                'start_odometer',
                'end_odometer',
                'fuel_consumed_liters',
                'status',
                'notes',
            ],
            'fields' => [
                'assignment_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'vehicle_id' => [
                    'label' => 'Vehicle',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'vehicles', 'key' => 'vehicle_id', 'label' => 'vehicle_code'],
                ],
                'employee_id' => [
                    'label' => 'Driver',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'employees', 'key' => 'employee_id', 'label' => 'employee_code'],
                ],
                'assignment_date' => ['label' => 'Assignment Date', 'type' => 'date', 'required' => true],
                'start_time' => ['label' => 'Start Time', 'type' => 'datetime'],
                'end_time' => ['label' => 'End Time', 'type' => 'datetime'],
                'start_odometer' => ['label' => 'Start Odometer', 'type' => 'number'],
                'end_odometer' => ['label' => 'End Odometer', 'type' => 'number'],
                'fuel_consumed_liters' => ['label' => 'Fuel Used (L)', 'type' => 'decimal'],
                'status' => [
                    'label' => 'Status',
                    'type' => 'select',
                    'options' => [
                        'assigned' => 'Assigned',
                        'in_progress' => 'In Progress',
                        'completed' => 'Completed',
                    ],
                    'default' => 'assigned',
                ],
                'notes' => ['label' => 'Notes', 'type' => 'textarea'],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'routes' => [
            'label' => 'Routes',
            'group' => 'Collections',
            'table' => 'routes',
            'primary' => 'route_id',
            'searchable' => ['route_name', 'route_code'],
            'list' => ['route_id', 'route_name', 'route_code', 'zone_id', 'priority_level', 'status'],
            'form' => [
                'route_name',
                'route_code',
                'zone_id',
                'estimated_duration_minutes',
                'total_distance_km',
                'priority_level',
                'status',
                'description',
            ],
            'fields' => [
                'route_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'route_name' => ['label' => 'Route Name', 'type' => 'text', 'required' => true],
                'route_code' => ['label' => 'Route Code', 'type' => 'text'],
                'zone_id' => [
                    'label' => 'Zone',
                    'type' => 'select',
                    'relation' => ['table' => 'zones', 'key' => 'zone_id', 'label' => 'zone_name'],
                ],
                'estimated_duration_minutes' => ['label' => 'Estimated Duration (min)', 'type' => 'number'],
                'total_distance_km' => ['label' => 'Total Distance (km)', 'type' => 'decimal'],
                'priority_level' => [
                    'label' => 'Priority Level',
                    'type' => 'select',
                    'options' => [
                        'low' => 'Low',
                        'medium' => 'Medium',
                        'high' => 'High',
                        'urgent' => 'Urgent',
                    ],
                    'default' => 'medium',
                ],
                'status' => [
                    'label' => 'Status',
                    'type' => 'select',
                    'options' => [
                        'active' => 'Active',
                        'inactive' => 'Inactive',
                        'temporary' => 'Temporary',
                    ],
                    'default' => 'active',
                ],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'route_containers' => [
            'label' => 'Route Containers',
            'group' => 'Collections',
            'table' => 'route_containers',
            'primary' => 'route_container_id',
            'searchable' => [],
            'list' => ['route_container_id', 'route_id', 'container_id', 'sequence_order'],
            'form' => ['route_id', 'container_id', 'sequence_order', 'estimated_time_minutes'],
            'fields' => [
                'route_container_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'route_id' => [
                    'label' => 'Route',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'routes', 'key' => 'route_id', 'label' => 'route_name'],
                ],
                'container_id' => [
                    'label' => 'Container',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'containers', 'key' => 'container_id', 'label' => 'container_code'],
                ],
                'sequence_order' => ['label' => 'Sequence Order', 'type' => 'number', 'required' => true],
                'estimated_time_minutes' => ['label' => 'Estimated Time (min)', 'type' => 'number'],
            ],
        ],
        'collection_schedules' => [
            'label' => 'Collection Schedules',
            'group' => 'Collections',
            'table' => 'collection_schedules',
            'primary' => 'schedule_id',
            'searchable' => ['notes'],
            'list' => ['schedule_id', 'route_id', 'scheduled_date', 'scheduled_start_time', 'status', 'vehicle_id', 'driver_id'],
            'form' => [
                'route_id',
                'vehicle_id',
                'driver_id',
                'partner_id',
                'scheduled_date',
                'scheduled_start_time',
                'actual_start_time',
                'actual_end_time',
                'status',
                'total_collected_kg',
                'notes',
            ],
            'fields' => [
                'schedule_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'route_id' => [
                    'label' => 'Route',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'routes', 'key' => 'route_id', 'label' => 'route_name'],
                ],
                'vehicle_id' => [
                    'label' => 'Vehicle',
                    'type' => 'select',
                    'relation' => ['table' => 'vehicles', 'key' => 'vehicle_id', 'label' => 'vehicle_code'],
                ],
                'driver_id' => [
                    'label' => 'Driver',
                    'type' => 'select',
                    'relation' => ['table' => 'employees', 'key' => 'employee_id', 'label' => 'employee_code'],
                ],
                'partner_id' => [
                    'label' => 'Partner',
                    'type' => 'select',
                    'relation' => ['table' => 'employees', 'key' => 'employee_id', 'label' => 'employee_code'],
                ],
                'scheduled_date' => ['label' => 'Scheduled Date', 'type' => 'date', 'required' => true],
                'scheduled_start_time' => ['label' => 'Scheduled Start Time', 'type' => 'time'],
                'actual_start_time' => ['label' => 'Actual Start Time', 'type' => 'datetime'],
                'actual_end_time' => ['label' => 'Actual End Time', 'type' => 'datetime'],
                'status' => [
                    'label' => 'Status',
                    'type' => 'select',
                    'options' => [
                        'scheduled' => 'Scheduled',
                        'in_progress' => 'In Progress',
                        'completed' => 'Completed',
                        'cancelled' => 'Cancelled',
                    ],
                    'default' => 'scheduled',
                ],
                'total_collected_kg' => ['label' => 'Total Collected (kg)', 'type' => 'decimal'],
                'notes' => ['label' => 'Notes', 'type' => 'textarea'],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'collection_reports' => [
            'label' => 'Collection Reports',
            'group' => 'Collections',
            'table' => 'collection_reports',
            'primary' => 'report_id',
            'searchable' => ['issues_reported'],
            'list' => ['report_id', 'schedule_id', 'container_id', 'collection_timestamp', 'collected_weight_kg', 'fill_level_before', 'fill_level_after'],
            'form' => [
                'schedule_id',
                'container_id',
                'collection_timestamp',
                'fill_level_before',
                'fill_level_after',
                'collected_weight_kg',
                'collection_duration_minutes',
                'issues_reported',
                'photo_url',
                'latitude',
                'longitude',
            ],
            'fields' => [
                'report_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'schedule_id' => [
                    'label' => 'Schedule',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'collection_schedules', 'key' => 'schedule_id', 'label' => 'schedule_id'],
                ],
                'container_id' => [
                    'label' => 'Container',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'containers', 'key' => 'container_id', 'label' => 'container_code'],
                ],
                'collection_timestamp' => ['label' => 'Collection Time', 'type' => 'datetime'],
                'fill_level_before' => ['label' => 'Fill Level Before', 'type' => 'decimal'],
                'fill_level_after' => ['label' => 'Fill Level After', 'type' => 'decimal', 'default' => 0],
                'collected_weight_kg' => ['label' => 'Collected Weight (kg)', 'type' => 'decimal'],
                'collection_duration_minutes' => ['label' => 'Collection Duration (min)', 'type' => 'number'],
                'issues_reported' => ['label' => 'Issues Reported', 'type' => 'textarea'],
                'photo_url' => ['label' => 'Photo URL', 'type' => 'text'],
                'latitude' => ['label' => 'Latitude', 'type' => 'decimal'],
                'longitude' => ['label' => 'Longitude', 'type' => 'decimal'],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'material_types' => [
            'label' => 'Material Types',
            'group' => 'Recycling',
            'table' => 'material_types',
            'primary' => 'material_id',
            'searchable' => ['material_name', 'description'],
            'list' => ['material_id', 'material_name', 'unit', 'recyclable'],
            'form' => ['material_name', 'description', 'unit', 'recyclable'],
            'fields' => [
                'material_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'material_name' => ['label' => 'Material Name', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'unit' => ['label' => 'Unit', 'type' => 'text', 'default' => 'kg'],
                'recyclable' => ['label' => 'Recyclable', 'type' => 'boolean', 'default' => true],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'partners' => [
            'label' => 'Partners',
            'group' => 'Recycling',
            'table' => 'partners',
            'primary' => 'partner_id',
            'searchable' => ['partner_name', 'contact_person', 'email'],
            'list' => ['partner_id', 'partner_name', 'partner_type', 'status', 'email', 'phone', 'rating'],
            'form' => [
                'partner_name',
                'contact_person',
                'email',
                'phone',
                'address',
                'partner_type',
                'status',
                'payment_terms',
                'rating',
                'notes',
            ],
            'fields' => [
                'partner_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'partner_name' => ['label' => 'Partner Name', 'type' => 'text', 'required' => true],
                'contact_person' => ['label' => 'Contact Person', 'type' => 'text'],
                'email' => ['label' => 'Email', 'type' => 'email'],
                'phone' => ['label' => 'Phone', 'type' => 'text'],
                'address' => ['label' => 'Address', 'type' => 'textarea'],
                'partner_type' => [
                    'label' => 'Partner Type',
                    'type' => 'select',
                    'options' => [
                        'buyer' => 'Buyer',
                        'recycler' => 'Recycler',
                        'processor' => 'Processor',
                        'supplier' => 'Supplier',
                    ],
                    'default' => 'buyer',
                ],
                'status' => [
                    'label' => 'Status',
                    'type' => 'select',
                    'options' => [
                        'active' => 'Active',
                        'inactive' => 'Inactive',
                        'blacklisted' => 'Blacklisted',
                    ],
                    'default' => 'active',
                ],
                'payment_terms' => ['label' => 'Payment Terms', 'type' => 'text'],
                'rating' => ['label' => 'Rating', 'type' => 'decimal'],
                'notes' => ['label' => 'Notes', 'type' => 'textarea'],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'partner_materials' => [
            'label' => 'Partner Materials',
            'group' => 'Recycling',
            'table' => 'partner_materials',
            'primary' => 'partner_material_id',
            'searchable' => [],
            'list' => ['partner_material_id', 'partner_id', 'material_id', 'current_price_per_kg', 'minimum_quantity_kg', 'last_price_update'],
            'form' => ['partner_id', 'material_id', 'current_price_per_kg', 'minimum_quantity_kg'],
            'fields' => [
                'partner_material_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'partner_id' => [
                    'label' => 'Partner',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'partners', 'key' => 'partner_id', 'label' => 'partner_name'],
                ],
                'material_id' => [
                    'label' => 'Material',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'material_types', 'key' => 'material_id', 'label' => 'material_name'],
                ],
                'current_price_per_kg' => ['label' => 'Price per kg', 'type' => 'decimal', 'required' => true],
                'minimum_quantity_kg' => ['label' => 'Minimum Quantity (kg)', 'type' => 'decimal'],
                'last_price_update' => ['label' => 'Last Price Update', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'material_inventory' => [
            'label' => 'Material Inventory',
            'group' => 'Recycling',
            'table' => 'material_inventory',
            'primary' => 'inventory_id',
            'searchable' => ['location'],
            'list' => ['inventory_id', 'material_id', 'quantity_kg', 'location', 'last_updated'],
            'form' => ['material_id', 'quantity_kg', 'location', 'notes'],
            'fields' => [
                'inventory_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'material_id' => [
                    'label' => 'Material',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'material_types', 'key' => 'material_id', 'label' => 'material_name'],
                ],
                'quantity_kg' => ['label' => 'Quantity (kg)', 'type' => 'decimal', 'required' => true],
                'location' => ['label' => 'Location', 'type' => 'text'],
                'notes' => ['label' => 'Notes', 'type' => 'textarea'],
                'last_updated' => ['label' => 'Last Updated', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'sales_transactions' => [
            'label' => 'Sales Transactions',
            'group' => 'Recycling',
            'table' => 'sales_transactions',
            'primary' => 'transaction_id',
            'searchable' => ['invoice_number', 'notes'],
            'list' => ['transaction_id', 'partner_id', 'material_id', 'quantity_kg', 'price_per_kg', 'total_amount', 'transaction_date', 'payment_status'],
            'form' => [
                'partner_id',
                'material_id',
                'quantity_kg',
                'price_per_kg',
                'transaction_date',
                'payment_status',
                'payment_date',
                'invoice_number',
                'notes',
                'created_by',
            ],
            'fields' => [
                'transaction_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'partner_id' => [
                    'label' => 'Partner',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'partners', 'key' => 'partner_id', 'label' => 'partner_name'],
                ],
                'material_id' => [
                    'label' => 'Material',
                    'type' => 'select',
                    'required' => true,
                    'relation' => ['table' => 'material_types', 'key' => 'material_id', 'label' => 'material_name'],
                ],
                'quantity_kg' => ['label' => 'Quantity (kg)', 'type' => 'decimal', 'required' => true],
                'price_per_kg' => ['label' => 'Price per kg', 'type' => 'decimal', 'required' => true],
                'total_amount' => ['label' => 'Total Amount', 'type' => 'decimal', 'readonly' => true],
                'transaction_date' => ['label' => 'Transaction Date', 'type' => 'date', 'required' => true],
                'payment_status' => [
                    'label' => 'Payment Status',
                    'type' => 'select',
                    'options' => [
                        'pending' => 'Pending',
                        'partial' => 'Partial',
                        'paid' => 'Paid',
                        'overdue' => 'Overdue',
                    ],
                    'default' => 'pending',
                ],
                'payment_date' => ['label' => 'Payment Date', 'type' => 'date'],
                'invoice_number' => ['label' => 'Invoice Number', 'type' => 'text'],
                'notes' => ['label' => 'Notes', 'type' => 'textarea'],
                'created_by' => [
                    'label' => 'Created By',
                    'type' => 'select',
                    'relation' => ['table' => 'users', 'key' => 'user_id', 'label' => 'full_name'],
                ],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
        'alerts' => [
            'label' => 'Alerts',
            'group' => 'Monitoring',
            'table' => 'alerts',
            'primary' => 'alert_id',
            'searchable' => ['title', 'message'],
            'list' => ['alert_id', 'alert_type', 'severity', 'title', 'is_read', 'is_resolved', 'created_at'],
            'form' => [
                'alert_type',
                'severity',
                'container_id',
                'vehicle_id',
                'route_id',
                'title',
                'message',
                'is_read',
                'is_resolved',
                'assigned_to',
                'resolved_by',
                'resolved_at',
            ],
            'fields' => [
                'alert_id' => ['label' => 'ID', 'type' => 'number', 'readonly' => true],
                'alert_type' => [
                    'label' => 'Alert Type',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'container_full' => 'Container Full',
                        'maintenance_due' => 'Maintenance Due',
                        'collection_delayed' => 'Collection Delayed',
                        'sensor_offline' => 'Sensor Offline',
                        'low_battery' => 'Low Battery',
                        'system' => 'System',
                    ],
                ],
                'severity' => [
                    'label' => 'Severity',
                    'type' => 'select',
                    'options' => [
                        'low' => 'Low',
                        'medium' => 'Medium',
                        'high' => 'High',
                        'critical' => 'Critical',
                    ],
                    'default' => 'medium',
                ],
                'container_id' => [
                    'label' => 'Container',
                    'type' => 'select',
                    'relation' => ['table' => 'containers', 'key' => 'container_id', 'label' => 'container_code'],
                ],
                'vehicle_id' => [
                    'label' => 'Vehicle',
                    'type' => 'select',
                    'relation' => ['table' => 'vehicles', 'key' => 'vehicle_id', 'label' => 'vehicle_code'],
                ],
                'route_id' => [
                    'label' => 'Route',
                    'type' => 'select',
                    'relation' => ['table' => 'routes', 'key' => 'route_id', 'label' => 'route_name'],
                ],
                'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
                'message' => ['label' => 'Message', 'type' => 'textarea', 'required' => true],
                'is_read' => ['label' => 'Read', 'type' => 'boolean', 'default' => false],
                'is_resolved' => ['label' => 'Resolved', 'type' => 'boolean', 'default' => false],
                'assigned_to' => [
                    'label' => 'Assigned To',
                    'type' => 'select',
                    'relation' => ['table' => 'users', 'key' => 'user_id', 'label' => 'full_name'],
                ],
                'resolved_by' => [
                    'label' => 'Resolved By',
                    'type' => 'select',
                    'relation' => ['table' => 'users', 'key' => 'user_id', 'label' => 'full_name'],
                ],
                'resolved_at' => ['label' => 'Resolved At', 'type' => 'datetime'],
                'created_at' => ['label' => 'Created', 'type' => 'datetime', 'readonly' => true],
            ],
        ],
    ],
];
